language: ruby
rvm:
  - "1.9.3"
install:
  - sudo apt-get update
  - sudo apt-get install virtualbox
  - sudo apt-get install vagrant
script:
  - cd /home/travis/d-grana/vagrant-spark-cluster/nodes/spark-worker1
  - vagrant up
